/*
 * File: app/view/ContentEditor.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ContentEditor', {
    extend: 'Ext.window.Window',
    alias: 'widget.contenteditor',

    requires: [
        'MyApp.view.ContentEditorViewModel',
        'MyApp.view.ContentEditorViewController',
        'Ext.form.Panel',
        'Ext.ux.form.TinyMceTextArea',
        'Ext.panel.Tool'
    ],

    config: {
        callback: null,
        scope: null,
        contentId: null
    },

    controller: 'contenteditor',
    viewModel: {
        type: 'contenteditor'
    },
    modal: true,
    autoShow: true,
    height: 600,
    width: 800,
    layout: 'fit',
    title: 'Edit Content',
    maximizable: true,

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Title'
                },
                {
                    xtype: 'tinymce',
                    anchor: '100% -40',
                    fieldLabel: 'Content',
                    labelAlign: 'top',
                    libraryUrl: 'https://cloud.tinymce.com/stable/tinymce.min.js',
                    plugin_fullscreen: true,
                    plugin_paste: true,
                    spellchecker_language: 'en',
                    statusbar: true,
                    showFormattingToolbar: true,
                    formattingToolbar: 'undo redo | bold italic underline strikethrough superscript subscript | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat'
                }
            ]
        }
    ],
    tools: [
        {
            xtype: 'tool',
            type: 'save'
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onWindowAfterRender',
            delay: 250
        }
    }

});