/*
 * File: app/view/ContentEditorViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ContentEditorViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.contenteditor',

    onWindowAfterRender: function(component, eOpts) {
        var view = this.getView();
        view.setLoading(true);

        var contentId = view.getContentId().substring(4);
        MyApp.model.Rule.load(view.getContentId(), {
            success: function(rec,res) {
                view.setLoading(false);
                vm.set('record',rec);
            },
            failure: function(rec,res) {
                view.setLoading(false);
                Ext.Msg.alert("Error","Could not read data from server.");
                view.close();
            },
            scope: this
        });
    }

});
