/*
 * File: app/view/MainContainer.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainContainer', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.maincontainer',

    requires: [
        'MyApp.view.MainContainerViewModel',
        'MyApp.view.MainContainerViewController',
        'MyApp.view.handbook.navigation.Navigation',
        'MyApp.view.handbook.content.Content',
        'Ext.tree.Panel'
    ],

    controller: 'maincontainer',
    viewModel: {
        type: 'maincontainer'
    },
    border: true,
    height: '100%',
    width: '100%',
    layout: 'border',

    items: [
        {
            xtype: 'navigation',
            reference: 'navigation',
            region: 'center',
            split: true
        },
        {
            xtype: 'displaycontent',
            region: 'east',
            split: true
        }
    ]

});