/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'MyApp.view.MyViewportViewController',
        'MyApp.view.handbook.navigation.Navigation',
        'MyApp.view.handbook.content.Content',
        'MyApp.view.handbook.header.Header',
        'Ext.tree.Panel'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },
    border: 1,
    height: 250,
    html: '<',
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'navigation',
            region: 'center',
            split: true,
            reference: 'navigation'
        },
        {
            xtype: 'displaycontent',
            region: 'east',
            split: true
        },
        {
            xtype: 'navigationheader',
            region: 'north'
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onViewportAfterRender',
            delay: 500
        }
    }

});