/*
 * File: app/model/Rule.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Rule', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.proxy.Ajax'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'bodyText'
        },
        {
            type: 'int',
            name: 'activeYn'
        }
    ],

    proxy: {
        type: 'ajax',
        api: {
            create: 'https://dev.gabar.org/handbook/components/HandbookRule.cfc?method=insertRecord',
            read: 'https://dev.gabar.org/handbook/components/HandbookRule.cfc?method=read',
            update: 'https://dev.gabar.org/handbook/components/HandbookRule.cfc?method=update',
            destroy: 'https://dev.gabar.org/handbook/components/HandbookRule.cfc?method=delete'
        },
        withCredentials: true
    }
});