/*
 * File: app/view/handbook/content/ContentViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.content.ContentViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mypanel11',

    initViewModel: function(vm) {
        vm.bind({
            bindTo: '{selectedNode}',
            deep: true
        }, this.onChangeSelection, this);

    },

    onChangeSelection: function(record) {

        var vm = this.getViewModel();
        vm.set('selectedVersionId',null);
        vm.set('versionsAvailable',false);
        if (record) {
            if (record.get('versions') && record.get('versions').length > 0) {
                var s = vm.get('ContentVersions');
                s.removeAll();
                s.add({
                    id: 0,
                    text: 'Current Version'
                });
                var versions = record.get('versions');
                for (var i=0; i<versions.length; i++) {
                    s.add({
                        id: i+1,
                        text: "Version " + versions[i].versionNumber
                    });
                }
                vm.set('versionsAvailable',true);
                vm.set('selectedVersionId',0);
            }
        }
    },

    changeVersion: function(combo, record, eOpts) {
        var id = record.get('id');
        var dataRec =  this.getViewModel().get('selectedNode');
        var versions = dataRec.get('versions');

        if (id == 0) {
            this.getView().setData([{
                title: dataRec.get('text'),
                content: dataRec.get('content'),
                depth: 4
            }]);
        } else {
            this.getView().setData([{
                title: dataRec.get('text'),
                content: versions[id - 1].content,
                depth: 4

            }]);
        }
    }

});
