/*
 * File: app/view/handbook/content/ContentViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.content.ContentViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.mypanel11',

    requires: [
        'Ext.data.Store',
        'Ext.data.field.Field'
    ],

    data: {
        selectedVersionId: 0,
        versionsAvailable: false
    },

    stores: {
        ContentVersions: {
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'text'
                }
            ]
        }
    }

});