/*
 * File: app/view/handbook/content/ContentViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.content.ContentViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mypanel11',

    changeVersion: function(combo, record, eOpts) {
        var id = record.get('id');
        var dataRec =  this.getViewModel().get('selectedNode');
        var versions = dataRec.get('versions');
        if (id == 0) {
            this.lookup('contentPnl').setData([{
                title: dataRec.get('text'),
                content: dataRec.get('content'),
                depth: dataRec.get('depth')
            }]);
        } else {
            this.lookup('contentPnl').setData([{
                title: dataRec.get('text'),
                content: versions[id - 1].content,
                depth: dataRec.get('depth')
            }]);
        }
    }

});
