/*
 * File: app/view/handbook/navigation/Buttonbar.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.navigation.Buttonbar', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.navigationbuttonbar',

    requires: [
        'MyApp.view.handbook.navigation.ButtonbarViewModel',
        'MyApp.view.handbook.navigation.ButtonbarViewController',
        'Ext.button.Button'
    ],

    controller: 'handbook.navigation.buttonbar',
    viewModel: {
        type: 'handbook.navigation.buttonbar'
    },
    cls: 'topborder',
    height: 50,
    bodyBorder: false,
    bodyPadding: 10,
    header: false,
    title: 'My Panel',

    layout: {
        type: 'hbox',
        align: 'middle',
        pack: 'center'
    },
    items: [
        {
            xtype: 'button',
            handler: 'onPrevTopic',
            flex: 1,
            margin: '0 5 0 0',
            text: '<< Previous',
            bind: {
                disabled: '{!prevNode}'
            }
        },
        {
            xtype: 'button',
            handler: 'onNextTopic',
            flex: 1,
            text: 'Next >>',
            bind: {
                disabled: '{!nextNode}'
            }
        }
    ]

});