/*
 * File: app/view/handbook/navigation/NavigationViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.navigation.NavigationViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.handbooktreenav',

    onExpandAll: function(owner, tool, event) {
        var store = this.getView().getStore();
        store.getRootNode().expandChildren(true);
    },

    onCollapseAll: function(owner, tool, event) {
        var store = this.getView().getStore();
        store.getRootNode().collapseChildren(true);

    },

    onTreepanelCheckChange: function(node, checked, e, eOpts) {
        var tree = this.getView();
        var nodes = tree.getChecked();

        this.getView().fireEvent('onmultiselectchange',this.getView(),nodes);
    },

    onTreepanelSelect: function(rowmodel, record, index, eOpts) {
        this.redirectTo('handbook/' + record.get('id'));
    }

});
