/*
 * File: app/view/handbook/navigation/Navigation.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.navigation.Navigation', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.navigation',

    requires: [
        'MyApp.view.handbook.navigation.NavigationViewModel',
        'MyApp.view.handbook.navigation.NavigationViewController',
        'MyApp.view.handbook.navigation.Buttonbar',
        'Ext.tree.View',
        'Ext.panel.Tool',
        'Ext.panel.Panel'
    ],

    controller: 'handbooktreenav',
    viewModel: {
        type: 'handbook.navigation.navigation'
    },
    reference: 'mytree',
    flex: 2,
    collapsible: false,
    title: 'Table of Contents',
    rootVisible: false,

    bind: {
        selection: '{selectedNode}',
        store: '{TableOfContents}'
    },
    tools: [
        {
            xtype: 'tool',
            callback: 'onExpandAll',
            tooltip: 'Expand All',
            type: 'expand'
        },
        {
            xtype: 'tool',
            callback: 'onCollapseAll',
            tooltip: 'Collapse All',
            type: 'collapse'
        },
        {
            xtype: 'tool',
            tooltip: 'Help',
            type: 'help'
        }
    ],
    listeners: {
        checkchange: 'onTreepanelCheckChange',
        select: 'onTreepanelSelect'
    },
    dockedItems: [
        {
            xtype: 'navigationbuttonbar',
            dock: 'bottom'
        }
    ]

});