/*
 * File: app/view/handbook/header/HeaderViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.header.HeaderViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.handbook.header.header',

    onPanelAfterRender: function(component, eOpts) {
        this.getView().setLoading(true);
        Ext.Ajax.request({
            url: 'http://dev.gabar.org/templates/includes/hbheader.cfm',
            success: function(req,res) {
                this.getView().setLoading(false);
                this.getView().update(req.responseText);
            },
            failure: function(req,res) {
                this.getView().setLoading(false);

            },
            scope: this
        });
    }

});
