/*
 * File: app/view/handbook/header/Header.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.handbook.header.Header', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.navigationheader',

    requires: [
        'MyApp.view.handbook.header.HeaderViewModel',
        'MyApp.view.handbook.header.HeaderViewController',
        'Ext.XTemplate'
    ],

    controller: 'handbook.header.header',
    viewModel: {
        type: 'handbook.header.header'
    },
    margin: 0,
    bodyCls: 'sbgbackground-d',
    bodyPadding: 5,
    header: false,
    title: 'header',

    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});